#!/bin/bash

echo "> Copying snippets into Atom..."

if cp $(dirname $0)/snippets.cson ~/.atom/snippets.cson
then
  echo "> ...Copy success!"
  echo "> Opening your new snippets in Atom."
  atom ~/.atom/snippets.cson
else
  echo "> ...Failure! Exit status: $?"
fi
