#!/bin/bash

clear

echo "> Copying snippets into Atom..."

cp $(dirname $0)/snippets.cson ~/.atom/snippets.cson

echo "> ...Copy success!"
echo "> Opening your new snippets in Atom."

atom ~/.atom/snippets.cson
